# Generated by Django 5.0.3 on 2024-04-28 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='type',
            field=models.CharField(choices=[('A', 'NOTIFICATION'), ('B', 'ALARM')], default='B', max_length=5),
        ),
        migrations.AddField(
            model_name='notice',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.user'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='belongingTask',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.task'),
        ),
        migrations.AlterField(
            model_name='projectlinkpr',
            name='ghpr_id',
            field=models.IntegerField(),
        ),
    ]
