# Generated by Django 5.0.4 on 2024-04-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.CharField(default='1233', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'NORMAL'), ('B', 'ILLEGAL'), ('C', 'ADMIN'), ('D', 'ASSISTANT')], max_length=2),
        ),
    ]
