# Generated by Django 5.0.3 on 2024-05-06 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='project_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.project'),
        ),
        migrations.AlterField(
            model_name='userproject',
            name='role',
            field=models.CharField(choices=[('A', 'NORMAL'), ('B', 'ADMIN'), ('C', 'DEVELOPER'), ('D', 'ASSISTANT'), ('E', 'ILLEGAL')], max_length=3),
        ),
    ]
