# Generated by Django 5.0.3 on 2024-04-17 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('A', 'COMPLETED'), ('B', 'INPROGRESS'), ('C', 'NOTSTART'), ('D', 'REVIEWING')], max_length=2),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('A', 'NORMAL'), ('B', 'ILLEGAL'), ('C', 'ADMIN'), ('D', 'ASSISTANT')], max_length=2),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
                ('repo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.repo')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='PullRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('A', 'OPEN'), ('B', 'MERGED'), ('C', 'CLOSED')], max_length=2)),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.project')),
            ],
        ),
        migrations.CreateModel(
            name='PrLinkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.task')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.user')),
                ('pr_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.pullrequest')),
            ],
        ),
    ]
