# Generated by Django 5.0.3 on 2024-04-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_notice_type_notice_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectlinkpr',
            name='comment',
            field=models.TextField(default='No comment'),
        ),
    ]
