# Generated by Django 5.0.3 on 2024-04-23 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_remove_task_link_pr_projectlinkpr_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='link_pr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.projectlinkpr'),
        ),
    ]
